### ISSUE TITLE
TypeError: Cannot redefine property: confirm

### ISSUE THREAD

**Issue by xurwxj** [yariksav/vuetify-dialog#79]
```
at Function.defineProperty ()
    at DialogManager.component (node_modules/vuetify-dialog/dist/vuetify-dialog.esm.js:720:0)
    at Object.install$1 [as install] (node_modules/vuetify-dialog/dist/vuetify-dialog.esm.js:2434:0)
    at Function.Vue.use (/Users/shining3d/projects/dental-cloud/node_modules/vue/dist/vue.runtime.common.dev.js:5087:22)
    at Module../src/plugins/vuetify.js (src/plugins/vuetify.js:15:3)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Module../src/main.js (src/main.js:1:0)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Module../src/entry-server.js (src/entry-server.js:1:0)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Object.0 (js/app.js:45781:18)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at js/app.js:118:18
    at Object. (js/app.js:121:10)
```
```
"vue": "^2.6.11",
    "vue-i18n": "^8.17.3",
    "vue-meta": "^2.3.3",
    "vue-router": "^3.1.6",
    "vue-server-renderer": "^2.6.0",
    "vuetify": "^2.2.11",
    "vuetify-dialog": "^2.0.3"
```
```
import Vue from 'vue';
import Vuetify from 'vuetify/lib';
import i18n from '../i18n';
import VuetifyDialog from "vuetify-dialog";
import "vuetify-dialog/dist/vuetify-dialog.min.css";

Vue.use(Vuetify);

const vuetify = new Vuetify({
  lang: {
    t: (key, ...params) => i18n.t(key, params),
  },
});

Vue.use(VuetifyDialog, {
  context: {
    vuetify
  }
});

export default vuetify;
```

**Comment by yariksav** [comment]
fixed
